### PR TITLE
T6637: py files filter added for unused import check

### PR DESCRIPTION
**Pull request by kumvijaya**
## Change Summary

T6637: py files filter added for unused import check

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6637

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by kumvijaya** [comment]
@MergifyIo backport equuleus

**Comment by kumvijaya** [comment]
@MergifyIo backport circinus

**Comment by kumvijaya** [comment]
@MergifyIo backport sagitta

**Comment by c-po** [comment]
NOTE: This PR will remove the PR comments. As this is a mandatory action, you can not Merge a PR unless the action succeeds.

**Comment by c-po** [comment]
Manually squashed the commits to not clutter the repo

**Review by c-po — APPROVED** [review]

**Pull request merged**
