### PR TITLE
T6606: conflict label name updated to match with mergify

### PR DESCRIPTION
**Pull request by kumvijaya**
## Change Summary

T6606: conflict label name updated to match with mergify

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Other (please describe):

## Related Task(s)

https://vyos.dev/T6606

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by kumvijaya** [comment]
@MergifyIo backport sagitta

**Comment by kumvijaya** [comment]
@MergifyIo backport equuleus

**Comment by kumvijaya** [comment]
@MergifyIo backport circinus

**Comment by kumvijaya** [comment]
@MergifyIo backport sagitta

**Review by dmbaturin — APPROVED** [review]

**Pull request merged**
