### PR TITLE
T6509: Add PR comment for unused import findings

### PR DESCRIPTION
**Pull request by kumvijaya**
## Change Summary

T6509: Add PR comment for unused import findings

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6509

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by kumvijaya** [comment]
@MergifyIo backport sagitta

**Comment by kumvijaya** [comment]
@MergifyIo backport equuleus

**Comment by kumvijaya** [comment]
@MergifyIo backport circinus

**Comment by c-po** [comment]
I do not know why this needs to be a reusable workflow as it's only used in vyos-1x.

**Comment by kumvijaya** [comment]
@c-po I thought it is used in many repos, 
but i think no harm in keeping it reusable, so that can be used in other repos as well later.
Still you prefer to move it to vyos-1x, can do
Please let me know.

**Comment by c-po** [comment]
> @c-po I thought it is used in many repos, but i think no harm in keeping it reusable, so that can be used in other repos as well later. Still you prefer to move it to vyos-1x, can do Please let me know.

We are shrinking the amount of repos in use and vyos-1x is the only one with a ton of Python code, please keep it local to vyos-1x

**Review by dmbaturin — APPROVED** [review]

**Pull request merged**
